### ISSUE TITLE
Add support for mypaint?

### ISSUE THREAD

**Issue by benrob0329** [minetest-mods/moreblocks#42]
Mypaint is a really nice painting mod, but requires other mods to define paintable nodes.

It would make sense to add it as a soft dependancy and impliment something for stairsplus, and other nodes.

https://github.com/DonBatman/mypaint_extras/blob/master/mypaint_wood/init.lua seems like a good start.

I'll help where I can, but my lua knolage is limited as is my time.

**Comment by sofar** [comment]
Moreblocks adds already a large amount of nodes, and making all of those paintable would create an enormous amount of nodes.

If someone really wants to do this, it should best be done in a separate mod, e.g. `moreblocks-mypaint`, so that moreblocks and mypaint can not cause a few thousand nodes to be added unwittingly by anyone accidentally installing these mods together.

**Comment by VanessaE** [comment]
This issue is obsolete now since the advent of hardware texture coloring.  See [Colored Woods](https://github.com/minetest-mods/coloredwood) mod (and [Unified Dyes](https://github.com/minetest-mods/unifieddyes)) for examples of how that feature can be used in the context of stairsplus.
