### ISSUE TITLE
Glass nodes lost their face direction and can no longer be rotated

### ISSUE THREAD

**Issue by gpcf** [minetest-mods/moreblocks#98]
After I pulled moreblocks today, all oriented glass nodes (glass slabs, glass slopes) are lying flat and can't be oriented with the screwdriver. This doesn't happen with any other blocks.

**Comment by jhcole** [comment]
Caused by cf1b054a998a67b06e97c2e022537bf8516abdfb, 6a996eb86ae447a156bcae53a1b23b62ca5d5bb9 and minetest/minetest_game@2f46103ff8fc6f0e9bf2cf6dc507ccc5f4fb6ea8.

 For some unknown reason `default:glass` and `obsidian:glass` have `paramtype2 = "glasslikeliquidlevel"`.  After the refactor of `stairsplus/registrations.lua`, all of the source node's defs are passed along to `stairsplus:register_all()`.  Prior to cf1b054a998a67b06e97c2e022537bf8516abdfb the paramtype2 setting was discarded.

I suggest dropping paramtype2 from glass nodes before registering them and will submit a pull request with that option shortly.  However, I would appreciate it if anyone can explain why they have `paramtype2 = "glasslikeliquidlevel"` in the first place.
